### ISSUE TITLE
Need id property in TicketTypePricing structure.

### ISSUE THREAD

**Issue by Danishkhan007** [seatsio/seatsio-ios#8]
We are implementing seatsio-iOS in our iOS app... we require to have id property in TicketTypePricing structure and its support in Pricing class .

We found id support in javascript lib. of seats.io. Since we have same API and need to have same implementation.
Can we have id property in TicketTypePricing structure. to configure seats.io, just like we have in javascript

And get back same selected id in selectedTicketTypeId property on selection of seat. 
As this will uniquely identifies selectedTicketType (during multi level)

**Comment by mroloux** [comment]
Hi!

Sorry for responding so late - I totally missed your message.

On `TicketTypePricing`, you can set

- `label`: this is the human-readable label for the ticket type
- `ticketType`: this is the technical ID

Does that work for you?

**Comment by mroloux** [comment]
I'm closing this issue - please reopen it if needed.
